# Generated by Django 4.2.20 on 2025-05-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogoOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Фамилия Имя')),
                ('contact', models.CharField(max_length=200, verbose_name='Контактный телефон или Телеграмм')),
                ('description', models.TextField(verbose_name='Какой логотип желаете заказать?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
